name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8, 11, 17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle (Java 8-16)
      if: matrix.java-version <= 16
      run: ./gradlew build
      
    - name: Manual build (Java 17+)
      if: matrix.java-version >= 17
      run: |
        mkdir -p build/classes/java/main build/libs
        javac -d build/classes/java/main -sourcepath src/main/java src/main/java/com/converter/CR3Converter.java
        echo "Main-Class: com.converter.CR3Converter" > build/MANIFEST.MF
        echo "Implementation-Title: CR3 to JPEG Converter" >> build/MANIFEST.MF
        echo "Implementation-Version: 1.0.0" >> build/MANIFEST.MF
        jar -cvfm build/libs/CR3Converter-all-1.0.0.jar build/MANIFEST.MF -C build/classes/java/main .
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cr3-converter-java-${{ matrix.java-version }}
        path: build/libs/*.jar
  
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with simple script
      run: |
        mkdir build\classes\java\main
        mkdir build\libs
        javac -d build\classes\java\main -sourcepath src\main\java src\main\java\com\converter\CR3Converter.java
        echo Main-Class: com.converter.CR3Converter> build\MANIFEST.MF
        echo Implementation-Title: CR3 to JPEG Converter>> build\MANIFEST.MF
        echo Implementation-Version: 1.0.0>> build\MANIFEST.MF
        jar -cvfm build\libs\CR3Converter-all-1.0.0.jar build\MANIFEST.MF -C build\classes\java\main .
    
    - name: Test batch launcher
      run: |
        echo "Testing if JAR was created successfully..."
        dir build\libs\
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cr3-converter-windows
        path: |
          build/libs/*.jar
          CR3Converter.bat
          CR3Converter.ps1
          build-simple.bat